Automate build process to change version - Issue 96
ear1grey/structured-start-tab pull request #137
Opened 2021-04-26 09:12 UTC by YassineSMR

We took the version of index.ts and sync it in other files

Fixes #96

Co-authored-by: @toto101230

2021-04-26 12:35 UTC, ear1grey requested changes

2021-04-26 12:35 UTC, ear1grey commented on autobuild.js
> +const fs = require('fs');
use the ES6 import syntax - `require` will die eventually,

2021-04-26 12:35 UTC, ear1grey commented on autobuild.js
> +readInterface.on('line', function(line) {
might it be easier / more reliable to `export` the version number and then `import` it?

2021-04-27 09:34 UTC, toto101230 commented
We managed to use import but we couldn't import index because it was having problems with chrome.

2021-04-28 21:31 UTC, merged

2021-04-29 11:42 UTC, ear1grey commented
Now this is finished, I think a better way to do it, so... reopened!

In TS there's a [--resolveJsonModule](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#new---resolvejsonmodule) compiler switch that when used allows `import` to load `.json` files (as `require`) previously did.

This means that:
 - [ ] `package.json` can be the authoritative source.
 - [ ] `version.js` can be removed
 - [ ] `index.ts` can `import` the `package.json` file for access to the version string
 - [ ] `manifest.json` can be updated by `autobuild.js` based on the version in `package.json`
 - [ ] `npm version` can become the preferred way of updating the version number (and adding tags to git).
 
 Thoughts @jacekkopecky?

2021-04-29 11:52 UTC, jacekkopecky commented
we can also have a `version` script in package.json (not `postversion` btw) that updates `manifest.json` with the new version from `package.json` (the `version` script runs when `npm version` has updated `package.json`); then manifest.json gets committed as part of the version commit.

As an added exercise, we could also have a pre-commit git check that only allows version changes in package.json in commits with the appropriate version tag, and maybe CI could also check this.